# Generated by Django 5.0.9 on 2024-09-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
